#!/usr/bin/env python3
"""Generate a dual-core wrapper (default: SweRV EH1 swerv -> swerv_dual.v).

Two instances share clk/rst_l; all other ports are duplicated with
_0 / _1 suffixes. The wrapper is intended for GDS-only flow bring-up:
no SRAM, pure std-cell netlist, ~2x a single core.

Usage:
  python3 gen_swerv_dual.py <rtl.v> <out.v> [top_module]
"""
import re
import sys

src = open(sys.argv[1]).read()
out = sys.argv[2]
top = sys.argv[3] if len(sys.argv) > 3 else "swerv"

m = re.search(r"module %s\s*\((.*?)\);\s*(.*?)\nendmodule" % re.escape(top), src, re.S)
if not m:
    raise SystemExit("module %s not found" % top)
ports_part, body = m.group(1), m.group(2)

names = [p.strip() for p in ports_part.split(",") if p.strip()]

decls = {}
pat = re.compile(r"^\s*(input|output)\s+(?:wire\s+)?(?:\[([^\]]+)\])?\s*([^;]+);", re.M)
for mm in pat.finditer(body):
    kind, rng = mm.group(1), mm.group(2)
    for ident in (i.strip() for i in mm.group(3).split(",") if i.strip()):
        decls[ident] = (kind, rng)

missing = [n for n in names if n not in decls]
if missing:
    raise SystemExit(f"missing declarations: {missing}")

shared = {"clk", "rst_l"}
core_ports = [n for n in names if n not in shared]

def port_decl(name, suffix):
    kind, rng = decls[name]
    return "  %s %s%s;" % (kind, ("[%s] " % rng) if rng else "", name + suffix)

def inst(suffix):
    conns = [".clk(clk)", ".rst_l(rst_l)"] + [".%s(%s_%s)" % (n, n, suffix) for n in core_ports]
    return "  %s u%s (\n    %s\n  );" % (top, suffix, ",\n    ".join(conns))

lines = []
lines.append("// Dual %s wrapper: two instances, shared clock/reset" % top)
lines.append("// Generated by gen_swerv_dual.py")
lines.append("module %s_dual (" % top)
lines.append("  " + ",\n  ".join(["clk", "rst_l"] + [n + "_0" for n in core_ports] + [n + "_1" for n in core_ports]))
lines.append(");")
lines.append("  input clk;")
lines.append("  input rst_l;")
for n in core_ports:
    lines.append(port_decl(n, "_0"))
    lines.append(port_decl(n, "_1"))
lines.append(inst("0"))
lines.append(inst("1"))
lines.append("endmodule")

open(out, "w").write("\n".join(lines) + "\n")
print("wrote %s: %d ports x2, shared clk/rst_l" % (out, len(core_ports)))
