#!/usr/bin/env python3
"""Generate a dual-core SweRV EH1 wrapper (swerv_dual.v).

Two swerv instances share clk/rst_l; all other ports are duplicated with
_0 / _1 suffixes. The wrapper is intended for GDS-only flow bring-up:
no SRAM, pure std-cell netlist, ~2x a single swerv core.

Usage:
  python3 gen_swerv_dual.py <swerv_wrapper.sv2v.v> <out.v>
"""
import re
import sys

src = open(sys.argv[1]).read()
out = sys.argv[2]

m = re.search(r"module swerv\s*\((.*?)\);\s*(.*?)\nendmodule", src, re.S)
if not m:
    raise SystemExit("module swerv not found")
ports_part, body = m.group(1), m.group(2)

names = [p.strip() for p in ports_part.split(",") if p.strip()]

decls = {}
pat = re.compile(r"^\s*(input|output)\s*(?:\[([^\]]+)\])?\s*([^;]+);", re.M)
for mm in pat.finditer(body):
    kind, rng = mm.group(1), mm.group(2)
    for ident in (i.strip() for i in mm.group(3).split(",") if i.strip()):
        decls[ident] = (kind, rng)

missing = [n for n in names if n not in decls]
if missing:
    raise SystemExit(f"missing declarations: {missing}")

shared = {"clk", "rst_l"}
core_ports = [n for n in names if n not in shared]

def port_decl(name, suffix):
    kind, rng = decls[name]
    return "  %s %s%s;" % (kind, ("[%s] " % rng) if rng else "", name + suffix)

def inst(suffix):
    conns = [".clk(clk)", ".rst_l(rst_l)"] + [".%s(%s_%s)" % (n, n, suffix) for n in core_ports]
    return "  swerv u%s (\n    %s\n  );" % (suffix, ",\n    ".join(conns))

lines = []
lines.append("// Dual SweRV EH1 wrapper: two swerv cores, shared clock/reset")
lines.append("// Generated by gen_swerv_dual.py")
lines.append("module swerv_dual (")
lines.append("  " + ",\n  ".join(["clk", "rst_l"] + [n + "_0" for n in core_ports] + [n + "_1" for n in core_ports]))
lines.append(");")
lines.append("  input clk;")
lines.append("  input rst_l;")
for n in core_ports:
    lines.append(port_decl(n, "_0"))
    lines.append(port_decl(n, "_1"))
lines.append(inst("0"))
lines.append(inst("1"))
lines.append("endmodule")

open(out, "w").write("\n".join(lines) + "\n")
print("wrote %s: %d ports x2, shared clk/rst_l" % (out, len(core_ports)))
