// Dual SweRV EH1 wrapper: two swerv cores, shared clock/reset
// Generated by gen_swerv_dual.py
module swerv_dual (
  clk,
  rst_l,
  rst_vec_0,
  nmi_int_0,
  nmi_vec_0,
  jtag_id_0,
  core_rst_l_0,
  trace_rv_i_insn_ip_0,
  trace_rv_i_address_ip_0,
  trace_rv_i_valid_ip_0,
  trace_rv_i_exception_ip_0,
  trace_rv_i_ecause_ip_0,
  trace_rv_i_interrupt_ip_0,
  trace_rv_i_tval_ip_0,
  lsu_freeze_dc3_0,
  dccm_clk_override_0,
  icm_clk_override_0,
  dec_tlu_core_ecc_disable_0,
  i_cpu_halt_req_0,
  i_cpu_run_req_0,
  o_cpu_halt_ack_0,
  o_cpu_halt_status_0,
  o_cpu_run_ack_0,
  o_debug_mode_status_0,
  mpc_debug_halt_req_0,
  mpc_debug_run_req_0,
  mpc_reset_run_req_0,
  mpc_debug_halt_ack_0,
  mpc_debug_run_ack_0,
  debug_brkpt_status_0,
  dec_tlu_perfcnt0_0,
  dec_tlu_perfcnt1_0,
  dec_tlu_perfcnt2_0,
  dec_tlu_perfcnt3_0,
  dccm_wren_0,
  dccm_rden_0,
  dccm_wr_addr_0,
  dccm_rd_addr_lo_0,
  dccm_rd_addr_hi_0,
  dccm_wr_data_0,
  dccm_rd_data_lo_0,
  dccm_rd_data_hi_0,
  ic_rw_addr_0,
  ic_tag_valid_0,
  ic_wr_en_0,
  ic_rd_en_0,
  ic_wr_data_0,
  ic_rd_data_0,
  ictag_debug_rd_data_0,
  ic_debug_wr_data_0,
  ic_premux_data_0,
  ic_sel_premux_data_0,
  ic_debug_addr_0,
  ic_debug_rd_en_0,
  ic_debug_wr_en_0,
  ic_debug_tag_array_0,
  ic_debug_way_0,
  ic_rd_hit_0,
  ic_tag_perr_0,
  lsu_axi_awvalid_0,
  lsu_axi_awready_0,
  lsu_axi_awid_0,
  lsu_axi_awaddr_0,
  lsu_axi_awregion_0,
  lsu_axi_awlen_0,
  lsu_axi_awsize_0,
  lsu_axi_awburst_0,
  lsu_axi_awlock_0,
  lsu_axi_awcache_0,
  lsu_axi_awprot_0,
  lsu_axi_awqos_0,
  lsu_axi_wvalid_0,
  lsu_axi_wready_0,
  lsu_axi_wdata_0,
  lsu_axi_wstrb_0,
  lsu_axi_wlast_0,
  lsu_axi_bvalid_0,
  lsu_axi_bready_0,
  lsu_axi_bresp_0,
  lsu_axi_bid_0,
  lsu_axi_arvalid_0,
  lsu_axi_arready_0,
  lsu_axi_arid_0,
  lsu_axi_araddr_0,
  lsu_axi_arregion_0,
  lsu_axi_arlen_0,
  lsu_axi_arsize_0,
  lsu_axi_arburst_0,
  lsu_axi_arlock_0,
  lsu_axi_arcache_0,
  lsu_axi_arprot_0,
  lsu_axi_arqos_0,
  lsu_axi_rvalid_0,
  lsu_axi_rready_0,
  lsu_axi_rid_0,
  lsu_axi_rdata_0,
  lsu_axi_rresp_0,
  lsu_axi_rlast_0,
  ifu_axi_awvalid_0,
  ifu_axi_awready_0,
  ifu_axi_awid_0,
  ifu_axi_awaddr_0,
  ifu_axi_awregion_0,
  ifu_axi_awlen_0,
  ifu_axi_awsize_0,
  ifu_axi_awburst_0,
  ifu_axi_awlock_0,
  ifu_axi_awcache_0,
  ifu_axi_awprot_0,
  ifu_axi_awqos_0,
  ifu_axi_wvalid_0,
  ifu_axi_wready_0,
  ifu_axi_wdata_0,
  ifu_axi_wstrb_0,
  ifu_axi_wlast_0,
  ifu_axi_bvalid_0,
  ifu_axi_bready_0,
  ifu_axi_bresp_0,
  ifu_axi_bid_0,
  ifu_axi_arvalid_0,
  ifu_axi_arready_0,
  ifu_axi_arid_0,
  ifu_axi_araddr_0,
  ifu_axi_arregion_0,
  ifu_axi_arlen_0,
  ifu_axi_arsize_0,
  ifu_axi_arburst_0,
  ifu_axi_arlock_0,
  ifu_axi_arcache_0,
  ifu_axi_arprot_0,
  ifu_axi_arqos_0,
  ifu_axi_rvalid_0,
  ifu_axi_rready_0,
  ifu_axi_rid_0,
  ifu_axi_rdata_0,
  ifu_axi_rresp_0,
  ifu_axi_rlast_0,
  sb_axi_awvalid_0,
  sb_axi_awready_0,
  sb_axi_awid_0,
  sb_axi_awaddr_0,
  sb_axi_awregion_0,
  sb_axi_awlen_0,
  sb_axi_awsize_0,
  sb_axi_awburst_0,
  sb_axi_awlock_0,
  sb_axi_awcache_0,
  sb_axi_awprot_0,
  sb_axi_awqos_0,
  sb_axi_wvalid_0,
  sb_axi_wready_0,
  sb_axi_wdata_0,
  sb_axi_wstrb_0,
  sb_axi_wlast_0,
  sb_axi_bvalid_0,
  sb_axi_bready_0,
  sb_axi_bresp_0,
  sb_axi_bid_0,
  sb_axi_arvalid_0,
  sb_axi_arready_0,
  sb_axi_arid_0,
  sb_axi_araddr_0,
  sb_axi_arregion_0,
  sb_axi_arlen_0,
  sb_axi_arsize_0,
  sb_axi_arburst_0,
  sb_axi_arlock_0,
  sb_axi_arcache_0,
  sb_axi_arprot_0,
  sb_axi_arqos_0,
  sb_axi_rvalid_0,
  sb_axi_rready_0,
  sb_axi_rid_0,
  sb_axi_rdata_0,
  sb_axi_rresp_0,
  sb_axi_rlast_0,
  dma_axi_awvalid_0,
  dma_axi_awready_0,
  dma_axi_awid_0,
  dma_axi_awaddr_0,
  dma_axi_awsize_0,
  dma_axi_awprot_0,
  dma_axi_awlen_0,
  dma_axi_awburst_0,
  dma_axi_wvalid_0,
  dma_axi_wready_0,
  dma_axi_wdata_0,
  dma_axi_wstrb_0,
  dma_axi_wlast_0,
  dma_axi_bvalid_0,
  dma_axi_bready_0,
  dma_axi_bresp_0,
  dma_axi_bid_0,
  dma_axi_arvalid_0,
  dma_axi_arready_0,
  dma_axi_arid_0,
  dma_axi_araddr_0,
  dma_axi_arsize_0,
  dma_axi_arprot_0,
  dma_axi_arlen_0,
  dma_axi_arburst_0,
  dma_axi_rvalid_0,
  dma_axi_rready_0,
  dma_axi_rid_0,
  dma_axi_rdata_0,
  dma_axi_rresp_0,
  dma_axi_rlast_0,
  lsu_bus_clk_en_0,
  ifu_bus_clk_en_0,
  dbg_bus_clk_en_0,
  dma_bus_clk_en_0,
  jtag_tck_0,
  jtag_tms_0,
  jtag_tdi_0,
  jtag_trst_n_0,
  jtag_tdo_0,
  extintsrc_req_0,
  timer_int_0,
  scan_mode_0,
  rst_vec_1,
  nmi_int_1,
  nmi_vec_1,
  jtag_id_1,
  core_rst_l_1,
  trace_rv_i_insn_ip_1,
  trace_rv_i_address_ip_1,
  trace_rv_i_valid_ip_1,
  trace_rv_i_exception_ip_1,
  trace_rv_i_ecause_ip_1,
  trace_rv_i_interrupt_ip_1,
  trace_rv_i_tval_ip_1,
  lsu_freeze_dc3_1,
  dccm_clk_override_1,
  icm_clk_override_1,
  dec_tlu_core_ecc_disable_1,
  i_cpu_halt_req_1,
  i_cpu_run_req_1,
  o_cpu_halt_ack_1,
  o_cpu_halt_status_1,
  o_cpu_run_ack_1,
  o_debug_mode_status_1,
  mpc_debug_halt_req_1,
  mpc_debug_run_req_1,
  mpc_reset_run_req_1,
  mpc_debug_halt_ack_1,
  mpc_debug_run_ack_1,
  debug_brkpt_status_1,
  dec_tlu_perfcnt0_1,
  dec_tlu_perfcnt1_1,
  dec_tlu_perfcnt2_1,
  dec_tlu_perfcnt3_1,
  dccm_wren_1,
  dccm_rden_1,
  dccm_wr_addr_1,
  dccm_rd_addr_lo_1,
  dccm_rd_addr_hi_1,
  dccm_wr_data_1,
  dccm_rd_data_lo_1,
  dccm_rd_data_hi_1,
  ic_rw_addr_1,
  ic_tag_valid_1,
  ic_wr_en_1,
  ic_rd_en_1,
  ic_wr_data_1,
  ic_rd_data_1,
  ictag_debug_rd_data_1,
  ic_debug_wr_data_1,
  ic_premux_data_1,
  ic_sel_premux_data_1,
  ic_debug_addr_1,
  ic_debug_rd_en_1,
  ic_debug_wr_en_1,
  ic_debug_tag_array_1,
  ic_debug_way_1,
  ic_rd_hit_1,
  ic_tag_perr_1,
  lsu_axi_awvalid_1,
  lsu_axi_awready_1,
  lsu_axi_awid_1,
  lsu_axi_awaddr_1,
  lsu_axi_awregion_1,
  lsu_axi_awlen_1,
  lsu_axi_awsize_1,
  lsu_axi_awburst_1,
  lsu_axi_awlock_1,
  lsu_axi_awcache_1,
  lsu_axi_awprot_1,
  lsu_axi_awqos_1,
  lsu_axi_wvalid_1,
  lsu_axi_wready_1,
  lsu_axi_wdata_1,
  lsu_axi_wstrb_1,
  lsu_axi_wlast_1,
  lsu_axi_bvalid_1,
  lsu_axi_bready_1,
  lsu_axi_bresp_1,
  lsu_axi_bid_1,
  lsu_axi_arvalid_1,
  lsu_axi_arready_1,
  lsu_axi_arid_1,
  lsu_axi_araddr_1,
  lsu_axi_arregion_1,
  lsu_axi_arlen_1,
  lsu_axi_arsize_1,
  lsu_axi_arburst_1,
  lsu_axi_arlock_1,
  lsu_axi_arcache_1,
  lsu_axi_arprot_1,
  lsu_axi_arqos_1,
  lsu_axi_rvalid_1,
  lsu_axi_rready_1,
  lsu_axi_rid_1,
  lsu_axi_rdata_1,
  lsu_axi_rresp_1,
  lsu_axi_rlast_1,
  ifu_axi_awvalid_1,
  ifu_axi_awready_1,
  ifu_axi_awid_1,
  ifu_axi_awaddr_1,
  ifu_axi_awregion_1,
  ifu_axi_awlen_1,
  ifu_axi_awsize_1,
  ifu_axi_awburst_1,
  ifu_axi_awlock_1,
  ifu_axi_awcache_1,
  ifu_axi_awprot_1,
  ifu_axi_awqos_1,
  ifu_axi_wvalid_1,
  ifu_axi_wready_1,
  ifu_axi_wdata_1,
  ifu_axi_wstrb_1,
  ifu_axi_wlast_1,
  ifu_axi_bvalid_1,
  ifu_axi_bready_1,
  ifu_axi_bresp_1,
  ifu_axi_bid_1,
  ifu_axi_arvalid_1,
  ifu_axi_arready_1,
  ifu_axi_arid_1,
  ifu_axi_araddr_1,
  ifu_axi_arregion_1,
  ifu_axi_arlen_1,
  ifu_axi_arsize_1,
  ifu_axi_arburst_1,
  ifu_axi_arlock_1,
  ifu_axi_arcache_1,
  ifu_axi_arprot_1,
  ifu_axi_arqos_1,
  ifu_axi_rvalid_1,
  ifu_axi_rready_1,
  ifu_axi_rid_1,
  ifu_axi_rdata_1,
  ifu_axi_rresp_1,
  ifu_axi_rlast_1,
  sb_axi_awvalid_1,
  sb_axi_awready_1,
  sb_axi_awid_1,
  sb_axi_awaddr_1,
  sb_axi_awregion_1,
  sb_axi_awlen_1,
  sb_axi_awsize_1,
  sb_axi_awburst_1,
  sb_axi_awlock_1,
  sb_axi_awcache_1,
  sb_axi_awprot_1,
  sb_axi_awqos_1,
  sb_axi_wvalid_1,
  sb_axi_wready_1,
  sb_axi_wdata_1,
  sb_axi_wstrb_1,
  sb_axi_wlast_1,
  sb_axi_bvalid_1,
  sb_axi_bready_1,
  sb_axi_bresp_1,
  sb_axi_bid_1,
  sb_axi_arvalid_1,
  sb_axi_arready_1,
  sb_axi_arid_1,
  sb_axi_araddr_1,
  sb_axi_arregion_1,
  sb_axi_arlen_1,
  sb_axi_arsize_1,
  sb_axi_arburst_1,
  sb_axi_arlock_1,
  sb_axi_arcache_1,
  sb_axi_arprot_1,
  sb_axi_arqos_1,
  sb_axi_rvalid_1,
  sb_axi_rready_1,
  sb_axi_rid_1,
  sb_axi_rdata_1,
  sb_axi_rresp_1,
  sb_axi_rlast_1,
  dma_axi_awvalid_1,
  dma_axi_awready_1,
  dma_axi_awid_1,
  dma_axi_awaddr_1,
  dma_axi_awsize_1,
  dma_axi_awprot_1,
  dma_axi_awlen_1,
  dma_axi_awburst_1,
  dma_axi_wvalid_1,
  dma_axi_wready_1,
  dma_axi_wdata_1,
  dma_axi_wstrb_1,
  dma_axi_wlast_1,
  dma_axi_bvalid_1,
  dma_axi_bready_1,
  dma_axi_bresp_1,
  dma_axi_bid_1,
  dma_axi_arvalid_1,
  dma_axi_arready_1,
  dma_axi_arid_1,
  dma_axi_araddr_1,
  dma_axi_arsize_1,
  dma_axi_arprot_1,
  dma_axi_arlen_1,
  dma_axi_arburst_1,
  dma_axi_rvalid_1,
  dma_axi_rready_1,
  dma_axi_rid_1,
  dma_axi_rdata_1,
  dma_axi_rresp_1,
  dma_axi_rlast_1,
  lsu_bus_clk_en_1,
  ifu_bus_clk_en_1,
  dbg_bus_clk_en_1,
  dma_bus_clk_en_1,
  jtag_tck_1,
  jtag_tms_1,
  jtag_tdi_1,
  jtag_trst_n_1,
  jtag_tdo_1,
  extintsrc_req_1,
  timer_int_1,
  scan_mode_1
);
  input clk;
  input rst_l;
  input [31:1] rst_vec_0;
  input [31:1] rst_vec_1;
  input nmi_int_0;
  input nmi_int_1;
  input [31:1] nmi_vec_0;
  input [31:1] nmi_vec_1;
  input [31:1] jtag_id_0;
  input [31:1] jtag_id_1;
  output core_rst_l_0;
  output core_rst_l_1;
  output [63:0] trace_rv_i_insn_ip_0;
  output [63:0] trace_rv_i_insn_ip_1;
  output [63:0] trace_rv_i_address_ip_0;
  output [63:0] trace_rv_i_address_ip_1;
  output [2:0] trace_rv_i_valid_ip_0;
  output [2:0] trace_rv_i_valid_ip_1;
  output [2:0] trace_rv_i_exception_ip_0;
  output [2:0] trace_rv_i_exception_ip_1;
  output [4:0] trace_rv_i_ecause_ip_0;
  output [4:0] trace_rv_i_ecause_ip_1;
  output [2:0] trace_rv_i_interrupt_ip_0;
  output [2:0] trace_rv_i_interrupt_ip_1;
  output [31:0] trace_rv_i_tval_ip_0;
  output [31:0] trace_rv_i_tval_ip_1;
  output lsu_freeze_dc3_0;
  output lsu_freeze_dc3_1;
  output dccm_clk_override_0;
  output dccm_clk_override_1;
  output icm_clk_override_0;
  output icm_clk_override_1;
  output dec_tlu_core_ecc_disable_0;
  output dec_tlu_core_ecc_disable_1;
  input i_cpu_halt_req_0;
  input i_cpu_halt_req_1;
  input i_cpu_run_req_0;
  input i_cpu_run_req_1;
  output o_cpu_halt_ack_0;
  output o_cpu_halt_ack_1;
  output o_cpu_halt_status_0;
  output o_cpu_halt_status_1;
  output o_cpu_run_ack_0;
  output o_cpu_run_ack_1;
  output o_debug_mode_status_0;
  output o_debug_mode_status_1;
  input mpc_debug_halt_req_0;
  input mpc_debug_halt_req_1;
  input mpc_debug_run_req_0;
  input mpc_debug_run_req_1;
  input mpc_reset_run_req_0;
  input mpc_reset_run_req_1;
  output mpc_debug_halt_ack_0;
  output mpc_debug_halt_ack_1;
  output mpc_debug_run_ack_0;
  output mpc_debug_run_ack_1;
  output debug_brkpt_status_0;
  output debug_brkpt_status_1;
  output [1:0] dec_tlu_perfcnt0_0;
  output [1:0] dec_tlu_perfcnt0_1;
  output [1:0] dec_tlu_perfcnt1_0;
  output [1:0] dec_tlu_perfcnt1_1;
  output [1:0] dec_tlu_perfcnt2_0;
  output [1:0] dec_tlu_perfcnt2_1;
  output [1:0] dec_tlu_perfcnt3_0;
  output [1:0] dec_tlu_perfcnt3_1;
  output dccm_wren_0;
  output dccm_wren_1;
  output dccm_rden_0;
  output dccm_rden_1;
  output [15:0] dccm_wr_addr_0;
  output [15:0] dccm_wr_addr_1;
  output [15:0] dccm_rd_addr_lo_0;
  output [15:0] dccm_rd_addr_lo_1;
  output [15:0] dccm_rd_addr_hi_0;
  output [15:0] dccm_rd_addr_hi_1;
  output [38:0] dccm_wr_data_0;
  output [38:0] dccm_wr_data_1;
  input [38:0] dccm_rd_data_lo_0;
  input [38:0] dccm_rd_data_lo_1;
  input [38:0] dccm_rd_data_hi_0;
  input [38:0] dccm_rd_data_hi_1;
  output [31:3] ic_rw_addr_0;
  output [31:3] ic_rw_addr_1;
  output [3:0] ic_tag_valid_0;
  output [3:0] ic_tag_valid_1;
  output [3:0] ic_wr_en_0;
  output [3:0] ic_wr_en_1;
  output ic_rd_en_0;
  output ic_rd_en_1;
  output [67:0] ic_wr_data_0;
  output [67:0] ic_wr_data_1;
  input [135:0] ic_rd_data_0;
  input [135:0] ic_rd_data_1;
  input [20:0] ictag_debug_rd_data_0;
  input [20:0] ictag_debug_rd_data_1;
  output [33:0] ic_debug_wr_data_0;
  output [33:0] ic_debug_wr_data_1;
  output [127:0] ic_premux_data_0;
  output [127:0] ic_premux_data_1;
  output ic_sel_premux_data_0;
  output ic_sel_premux_data_1;
  output [15:2] ic_debug_addr_0;
  output [15:2] ic_debug_addr_1;
  output ic_debug_rd_en_0;
  output ic_debug_rd_en_1;
  output ic_debug_wr_en_0;
  output ic_debug_wr_en_1;
  output ic_debug_tag_array_0;
  output ic_debug_tag_array_1;
  output [3:0] ic_debug_way_0;
  output [3:0] ic_debug_way_1;
  input [3:0] ic_rd_hit_0;
  input [3:0] ic_rd_hit_1;
  input ic_tag_perr_0;
  input ic_tag_perr_1;
  output lsu_axi_awvalid_0;
  output lsu_axi_awvalid_1;
  input lsu_axi_awready_0;
  input lsu_axi_awready_1;
  output [3:0] lsu_axi_awid_0;
  output [3:0] lsu_axi_awid_1;
  output [31:0] lsu_axi_awaddr_0;
  output [31:0] lsu_axi_awaddr_1;
  output [3:0] lsu_axi_awregion_0;
  output [3:0] lsu_axi_awregion_1;
  output [7:0] lsu_axi_awlen_0;
  output [7:0] lsu_axi_awlen_1;
  output [2:0] lsu_axi_awsize_0;
  output [2:0] lsu_axi_awsize_1;
  output [1:0] lsu_axi_awburst_0;
  output [1:0] lsu_axi_awburst_1;
  output lsu_axi_awlock_0;
  output lsu_axi_awlock_1;
  output [3:0] lsu_axi_awcache_0;
  output [3:0] lsu_axi_awcache_1;
  output [2:0] lsu_axi_awprot_0;
  output [2:0] lsu_axi_awprot_1;
  output [3:0] lsu_axi_awqos_0;
  output [3:0] lsu_axi_awqos_1;
  output lsu_axi_wvalid_0;
  output lsu_axi_wvalid_1;
  input lsu_axi_wready_0;
  input lsu_axi_wready_1;
  output [63:0] lsu_axi_wdata_0;
  output [63:0] lsu_axi_wdata_1;
  output [7:0] lsu_axi_wstrb_0;
  output [7:0] lsu_axi_wstrb_1;
  output lsu_axi_wlast_0;
  output lsu_axi_wlast_1;
  input lsu_axi_bvalid_0;
  input lsu_axi_bvalid_1;
  output lsu_axi_bready_0;
  output lsu_axi_bready_1;
  input [1:0] lsu_axi_bresp_0;
  input [1:0] lsu_axi_bresp_1;
  input [3:0] lsu_axi_bid_0;
  input [3:0] lsu_axi_bid_1;
  output lsu_axi_arvalid_0;
  output lsu_axi_arvalid_1;
  input lsu_axi_arready_0;
  input lsu_axi_arready_1;
  output [3:0] lsu_axi_arid_0;
  output [3:0] lsu_axi_arid_1;
  output [31:0] lsu_axi_araddr_0;
  output [31:0] lsu_axi_araddr_1;
  output [3:0] lsu_axi_arregion_0;
  output [3:0] lsu_axi_arregion_1;
  output [7:0] lsu_axi_arlen_0;
  output [7:0] lsu_axi_arlen_1;
  output [2:0] lsu_axi_arsize_0;
  output [2:0] lsu_axi_arsize_1;
  output [1:0] lsu_axi_arburst_0;
  output [1:0] lsu_axi_arburst_1;
  output lsu_axi_arlock_0;
  output lsu_axi_arlock_1;
  output [3:0] lsu_axi_arcache_0;
  output [3:0] lsu_axi_arcache_1;
  output [2:0] lsu_axi_arprot_0;
  output [2:0] lsu_axi_arprot_1;
  output [3:0] lsu_axi_arqos_0;
  output [3:0] lsu_axi_arqos_1;
  input lsu_axi_rvalid_0;
  input lsu_axi_rvalid_1;
  output lsu_axi_rready_0;
  output lsu_axi_rready_1;
  input [3:0] lsu_axi_rid_0;
  input [3:0] lsu_axi_rid_1;
  input [63:0] lsu_axi_rdata_0;
  input [63:0] lsu_axi_rdata_1;
  input [1:0] lsu_axi_rresp_0;
  input [1:0] lsu_axi_rresp_1;
  input lsu_axi_rlast_0;
  input lsu_axi_rlast_1;
  output ifu_axi_awvalid_0;
  output ifu_axi_awvalid_1;
  input ifu_axi_awready_0;
  input ifu_axi_awready_1;
  output [2:0] ifu_axi_awid_0;
  output [2:0] ifu_axi_awid_1;
  output [31:0] ifu_axi_awaddr_0;
  output [31:0] ifu_axi_awaddr_1;
  output [3:0] ifu_axi_awregion_0;
  output [3:0] ifu_axi_awregion_1;
  output [7:0] ifu_axi_awlen_0;
  output [7:0] ifu_axi_awlen_1;
  output [2:0] ifu_axi_awsize_0;
  output [2:0] ifu_axi_awsize_1;
  output [1:0] ifu_axi_awburst_0;
  output [1:0] ifu_axi_awburst_1;
  output ifu_axi_awlock_0;
  output ifu_axi_awlock_1;
  output [3:0] ifu_axi_awcache_0;
  output [3:0] ifu_axi_awcache_1;
  output [2:0] ifu_axi_awprot_0;
  output [2:0] ifu_axi_awprot_1;
  output [3:0] ifu_axi_awqos_0;
  output [3:0] ifu_axi_awqos_1;
  output ifu_axi_wvalid_0;
  output ifu_axi_wvalid_1;
  input ifu_axi_wready_0;
  input ifu_axi_wready_1;
  output [63:0] ifu_axi_wdata_0;
  output [63:0] ifu_axi_wdata_1;
  output [7:0] ifu_axi_wstrb_0;
  output [7:0] ifu_axi_wstrb_1;
  output ifu_axi_wlast_0;
  output ifu_axi_wlast_1;
  input ifu_axi_bvalid_0;
  input ifu_axi_bvalid_1;
  output ifu_axi_bready_0;
  output ifu_axi_bready_1;
  input [1:0] ifu_axi_bresp_0;
  input [1:0] ifu_axi_bresp_1;
  input [2:0] ifu_axi_bid_0;
  input [2:0] ifu_axi_bid_1;
  output ifu_axi_arvalid_0;
  output ifu_axi_arvalid_1;
  input ifu_axi_arready_0;
  input ifu_axi_arready_1;
  output [2:0] ifu_axi_arid_0;
  output [2:0] ifu_axi_arid_1;
  output [31:0] ifu_axi_araddr_0;
  output [31:0] ifu_axi_araddr_1;
  output [3:0] ifu_axi_arregion_0;
  output [3:0] ifu_axi_arregion_1;
  output [7:0] ifu_axi_arlen_0;
  output [7:0] ifu_axi_arlen_1;
  output [2:0] ifu_axi_arsize_0;
  output [2:0] ifu_axi_arsize_1;
  output [1:0] ifu_axi_arburst_0;
  output [1:0] ifu_axi_arburst_1;
  output ifu_axi_arlock_0;
  output ifu_axi_arlock_1;
  output [3:0] ifu_axi_arcache_0;
  output [3:0] ifu_axi_arcache_1;
  output [2:0] ifu_axi_arprot_0;
  output [2:0] ifu_axi_arprot_1;
  output [3:0] ifu_axi_arqos_0;
  output [3:0] ifu_axi_arqos_1;
  input ifu_axi_rvalid_0;
  input ifu_axi_rvalid_1;
  output ifu_axi_rready_0;
  output ifu_axi_rready_1;
  input [2:0] ifu_axi_rid_0;
  input [2:0] ifu_axi_rid_1;
  input [63:0] ifu_axi_rdata_0;
  input [63:0] ifu_axi_rdata_1;
  input [1:0] ifu_axi_rresp_0;
  input [1:0] ifu_axi_rresp_1;
  input ifu_axi_rlast_0;
  input ifu_axi_rlast_1;
  output sb_axi_awvalid_0;
  output sb_axi_awvalid_1;
  input sb_axi_awready_0;
  input sb_axi_awready_1;
  output [0:0] sb_axi_awid_0;
  output [0:0] sb_axi_awid_1;
  output [31:0] sb_axi_awaddr_0;
  output [31:0] sb_axi_awaddr_1;
  output [3:0] sb_axi_awregion_0;
  output [3:0] sb_axi_awregion_1;
  output [7:0] sb_axi_awlen_0;
  output [7:0] sb_axi_awlen_1;
  output [2:0] sb_axi_awsize_0;
  output [2:0] sb_axi_awsize_1;
  output [1:0] sb_axi_awburst_0;
  output [1:0] sb_axi_awburst_1;
  output sb_axi_awlock_0;
  output sb_axi_awlock_1;
  output [3:0] sb_axi_awcache_0;
  output [3:0] sb_axi_awcache_1;
  output [2:0] sb_axi_awprot_0;
  output [2:0] sb_axi_awprot_1;
  output [3:0] sb_axi_awqos_0;
  output [3:0] sb_axi_awqos_1;
  output sb_axi_wvalid_0;
  output sb_axi_wvalid_1;
  input sb_axi_wready_0;
  input sb_axi_wready_1;
  output [63:0] sb_axi_wdata_0;
  output [63:0] sb_axi_wdata_1;
  output [7:0] sb_axi_wstrb_0;
  output [7:0] sb_axi_wstrb_1;
  output sb_axi_wlast_0;
  output sb_axi_wlast_1;
  input sb_axi_bvalid_0;
  input sb_axi_bvalid_1;
  output sb_axi_bready_0;
  output sb_axi_bready_1;
  input [1:0] sb_axi_bresp_0;
  input [1:0] sb_axi_bresp_1;
  input [0:0] sb_axi_bid_0;
  input [0:0] sb_axi_bid_1;
  output sb_axi_arvalid_0;
  output sb_axi_arvalid_1;
  input sb_axi_arready_0;
  input sb_axi_arready_1;
  output [0:0] sb_axi_arid_0;
  output [0:0] sb_axi_arid_1;
  output [31:0] sb_axi_araddr_0;
  output [31:0] sb_axi_araddr_1;
  output [3:0] sb_axi_arregion_0;
  output [3:0] sb_axi_arregion_1;
  output [7:0] sb_axi_arlen_0;
  output [7:0] sb_axi_arlen_1;
  output [2:0] sb_axi_arsize_0;
  output [2:0] sb_axi_arsize_1;
  output [1:0] sb_axi_arburst_0;
  output [1:0] sb_axi_arburst_1;
  output sb_axi_arlock_0;
  output sb_axi_arlock_1;
  output [3:0] sb_axi_arcache_0;
  output [3:0] sb_axi_arcache_1;
  output [2:0] sb_axi_arprot_0;
  output [2:0] sb_axi_arprot_1;
  output [3:0] sb_axi_arqos_0;
  output [3:0] sb_axi_arqos_1;
  input sb_axi_rvalid_0;
  input sb_axi_rvalid_1;
  output sb_axi_rready_0;
  output sb_axi_rready_1;
  input [0:0] sb_axi_rid_0;
  input [0:0] sb_axi_rid_1;
  input [63:0] sb_axi_rdata_0;
  input [63:0] sb_axi_rdata_1;
  input [1:0] sb_axi_rresp_0;
  input [1:0] sb_axi_rresp_1;
  input sb_axi_rlast_0;
  input sb_axi_rlast_1;
  input dma_axi_awvalid_0;
  input dma_axi_awvalid_1;
  output dma_axi_awready_0;
  output dma_axi_awready_1;
  input [0:0] dma_axi_awid_0;
  input [0:0] dma_axi_awid_1;
  input [31:0] dma_axi_awaddr_0;
  input [31:0] dma_axi_awaddr_1;
  input [2:0] dma_axi_awsize_0;
  input [2:0] dma_axi_awsize_1;
  input [2:0] dma_axi_awprot_0;
  input [2:0] dma_axi_awprot_1;
  input [7:0] dma_axi_awlen_0;
  input [7:0] dma_axi_awlen_1;
  input [1:0] dma_axi_awburst_0;
  input [1:0] dma_axi_awburst_1;
  input dma_axi_wvalid_0;
  input dma_axi_wvalid_1;
  output dma_axi_wready_0;
  output dma_axi_wready_1;
  input [63:0] dma_axi_wdata_0;
  input [63:0] dma_axi_wdata_1;
  input [7:0] dma_axi_wstrb_0;
  input [7:0] dma_axi_wstrb_1;
  input dma_axi_wlast_0;
  input dma_axi_wlast_1;
  output dma_axi_bvalid_0;
  output dma_axi_bvalid_1;
  input dma_axi_bready_0;
  input dma_axi_bready_1;
  output [1:0] dma_axi_bresp_0;
  output [1:0] dma_axi_bresp_1;
  output [0:0] dma_axi_bid_0;
  output [0:0] dma_axi_bid_1;
  input dma_axi_arvalid_0;
  input dma_axi_arvalid_1;
  output dma_axi_arready_0;
  output dma_axi_arready_1;
  input [0:0] dma_axi_arid_0;
  input [0:0] dma_axi_arid_1;
  input [31:0] dma_axi_araddr_0;
  input [31:0] dma_axi_araddr_1;
  input [2:0] dma_axi_arsize_0;
  input [2:0] dma_axi_arsize_1;
  input [2:0] dma_axi_arprot_0;
  input [2:0] dma_axi_arprot_1;
  input [7:0] dma_axi_arlen_0;
  input [7:0] dma_axi_arlen_1;
  input [1:0] dma_axi_arburst_0;
  input [1:0] dma_axi_arburst_1;
  output dma_axi_rvalid_0;
  output dma_axi_rvalid_1;
  input dma_axi_rready_0;
  input dma_axi_rready_1;
  output [0:0] dma_axi_rid_0;
  output [0:0] dma_axi_rid_1;
  output [63:0] dma_axi_rdata_0;
  output [63:0] dma_axi_rdata_1;
  output [1:0] dma_axi_rresp_0;
  output [1:0] dma_axi_rresp_1;
  output dma_axi_rlast_0;
  output dma_axi_rlast_1;
  input lsu_bus_clk_en_0;
  input lsu_bus_clk_en_1;
  input ifu_bus_clk_en_0;
  input ifu_bus_clk_en_1;
  input dbg_bus_clk_en_0;
  input dbg_bus_clk_en_1;
  input dma_bus_clk_en_0;
  input dma_bus_clk_en_1;
  input jtag_tck_0;
  input jtag_tck_1;
  input jtag_tms_0;
  input jtag_tms_1;
  input jtag_tdi_0;
  input jtag_tdi_1;
  input jtag_trst_n_0;
  input jtag_trst_n_1;
  output jtag_tdo_0;
  output jtag_tdo_1;
  input [8:1] extintsrc_req_0;
  input [8:1] extintsrc_req_1;
  input timer_int_0;
  input timer_int_1;
  input scan_mode_0;
  input scan_mode_1;
  swerv u0 (
    .clk(clk),
    .rst_l(rst_l),
    .rst_vec(rst_vec_0),
    .nmi_int(nmi_int_0),
    .nmi_vec(nmi_vec_0),
    .jtag_id(jtag_id_0),
    .core_rst_l(core_rst_l_0),
    .trace_rv_i_insn_ip(trace_rv_i_insn_ip_0),
    .trace_rv_i_address_ip(trace_rv_i_address_ip_0),
    .trace_rv_i_valid_ip(trace_rv_i_valid_ip_0),
    .trace_rv_i_exception_ip(trace_rv_i_exception_ip_0),
    .trace_rv_i_ecause_ip(trace_rv_i_ecause_ip_0),
    .trace_rv_i_interrupt_ip(trace_rv_i_interrupt_ip_0),
    .trace_rv_i_tval_ip(trace_rv_i_tval_ip_0),
    .lsu_freeze_dc3(lsu_freeze_dc3_0),
    .dccm_clk_override(dccm_clk_override_0),
    .icm_clk_override(icm_clk_override_0),
    .dec_tlu_core_ecc_disable(dec_tlu_core_ecc_disable_0),
    .i_cpu_halt_req(i_cpu_halt_req_0),
    .i_cpu_run_req(i_cpu_run_req_0),
    .o_cpu_halt_ack(o_cpu_halt_ack_0),
    .o_cpu_halt_status(o_cpu_halt_status_0),
    .o_cpu_run_ack(o_cpu_run_ack_0),
    .o_debug_mode_status(o_debug_mode_status_0),
    .mpc_debug_halt_req(mpc_debug_halt_req_0),
    .mpc_debug_run_req(mpc_debug_run_req_0),
    .mpc_reset_run_req(mpc_reset_run_req_0),
    .mpc_debug_halt_ack(mpc_debug_halt_ack_0),
    .mpc_debug_run_ack(mpc_debug_run_ack_0),
    .debug_brkpt_status(debug_brkpt_status_0),
    .dec_tlu_perfcnt0(dec_tlu_perfcnt0_0),
    .dec_tlu_perfcnt1(dec_tlu_perfcnt1_0),
    .dec_tlu_perfcnt2(dec_tlu_perfcnt2_0),
    .dec_tlu_perfcnt3(dec_tlu_perfcnt3_0),
    .dccm_wren(dccm_wren_0),
    .dccm_rden(dccm_rden_0),
    .dccm_wr_addr(dccm_wr_addr_0),
    .dccm_rd_addr_lo(dccm_rd_addr_lo_0),
    .dccm_rd_addr_hi(dccm_rd_addr_hi_0),
    .dccm_wr_data(dccm_wr_data_0),
    .dccm_rd_data_lo(dccm_rd_data_lo_0),
    .dccm_rd_data_hi(dccm_rd_data_hi_0),
    .ic_rw_addr(ic_rw_addr_0),
    .ic_tag_valid(ic_tag_valid_0),
    .ic_wr_en(ic_wr_en_0),
    .ic_rd_en(ic_rd_en_0),
    .ic_wr_data(ic_wr_data_0),
    .ic_rd_data(ic_rd_data_0),
    .ictag_debug_rd_data(ictag_debug_rd_data_0),
    .ic_debug_wr_data(ic_debug_wr_data_0),
    .ic_premux_data(ic_premux_data_0),
    .ic_sel_premux_data(ic_sel_premux_data_0),
    .ic_debug_addr(ic_debug_addr_0),
    .ic_debug_rd_en(ic_debug_rd_en_0),
    .ic_debug_wr_en(ic_debug_wr_en_0),
    .ic_debug_tag_array(ic_debug_tag_array_0),
    .ic_debug_way(ic_debug_way_0),
    .ic_rd_hit(ic_rd_hit_0),
    .ic_tag_perr(ic_tag_perr_0),
    .lsu_axi_awvalid(lsu_axi_awvalid_0),
    .lsu_axi_awready(lsu_axi_awready_0),
    .lsu_axi_awid(lsu_axi_awid_0),
    .lsu_axi_awaddr(lsu_axi_awaddr_0),
    .lsu_axi_awregion(lsu_axi_awregion_0),
    .lsu_axi_awlen(lsu_axi_awlen_0),
    .lsu_axi_awsize(lsu_axi_awsize_0),
    .lsu_axi_awburst(lsu_axi_awburst_0),
    .lsu_axi_awlock(lsu_axi_awlock_0),
    .lsu_axi_awcache(lsu_axi_awcache_0),
    .lsu_axi_awprot(lsu_axi_awprot_0),
    .lsu_axi_awqos(lsu_axi_awqos_0),
    .lsu_axi_wvalid(lsu_axi_wvalid_0),
    .lsu_axi_wready(lsu_axi_wready_0),
    .lsu_axi_wdata(lsu_axi_wdata_0),
    .lsu_axi_wstrb(lsu_axi_wstrb_0),
    .lsu_axi_wlast(lsu_axi_wlast_0),
    .lsu_axi_bvalid(lsu_axi_bvalid_0),
    .lsu_axi_bready(lsu_axi_bready_0),
    .lsu_axi_bresp(lsu_axi_bresp_0),
    .lsu_axi_bid(lsu_axi_bid_0),
    .lsu_axi_arvalid(lsu_axi_arvalid_0),
    .lsu_axi_arready(lsu_axi_arready_0),
    .lsu_axi_arid(lsu_axi_arid_0),
    .lsu_axi_araddr(lsu_axi_araddr_0),
    .lsu_axi_arregion(lsu_axi_arregion_0),
    .lsu_axi_arlen(lsu_axi_arlen_0),
    .lsu_axi_arsize(lsu_axi_arsize_0),
    .lsu_axi_arburst(lsu_axi_arburst_0),
    .lsu_axi_arlock(lsu_axi_arlock_0),
    .lsu_axi_arcache(lsu_axi_arcache_0),
    .lsu_axi_arprot(lsu_axi_arprot_0),
    .lsu_axi_arqos(lsu_axi_arqos_0),
    .lsu_axi_rvalid(lsu_axi_rvalid_0),
    .lsu_axi_rready(lsu_axi_rready_0),
    .lsu_axi_rid(lsu_axi_rid_0),
    .lsu_axi_rdata(lsu_axi_rdata_0),
    .lsu_axi_rresp(lsu_axi_rresp_0),
    .lsu_axi_rlast(lsu_axi_rlast_0),
    .ifu_axi_awvalid(ifu_axi_awvalid_0),
    .ifu_axi_awready(ifu_axi_awready_0),
    .ifu_axi_awid(ifu_axi_awid_0),
    .ifu_axi_awaddr(ifu_axi_awaddr_0),
    .ifu_axi_awregion(ifu_axi_awregion_0),
    .ifu_axi_awlen(ifu_axi_awlen_0),
    .ifu_axi_awsize(ifu_axi_awsize_0),
    .ifu_axi_awburst(ifu_axi_awburst_0),
    .ifu_axi_awlock(ifu_axi_awlock_0),
    .ifu_axi_awcache(ifu_axi_awcache_0),
    .ifu_axi_awprot(ifu_axi_awprot_0),
    .ifu_axi_awqos(ifu_axi_awqos_0),
    .ifu_axi_wvalid(ifu_axi_wvalid_0),
    .ifu_axi_wready(ifu_axi_wready_0),
    .ifu_axi_wdata(ifu_axi_wdata_0),
    .ifu_axi_wstrb(ifu_axi_wstrb_0),
    .ifu_axi_wlast(ifu_axi_wlast_0),
    .ifu_axi_bvalid(ifu_axi_bvalid_0),
    .ifu_axi_bready(ifu_axi_bready_0),
    .ifu_axi_bresp(ifu_axi_bresp_0),
    .ifu_axi_bid(ifu_axi_bid_0),
    .ifu_axi_arvalid(ifu_axi_arvalid_0),
    .ifu_axi_arready(ifu_axi_arready_0),
    .ifu_axi_arid(ifu_axi_arid_0),
    .ifu_axi_araddr(ifu_axi_araddr_0),
    .ifu_axi_arregion(ifu_axi_arregion_0),
    .ifu_axi_arlen(ifu_axi_arlen_0),
    .ifu_axi_arsize(ifu_axi_arsize_0),
    .ifu_axi_arburst(ifu_axi_arburst_0),
    .ifu_axi_arlock(ifu_axi_arlock_0),
    .ifu_axi_arcache(ifu_axi_arcache_0),
    .ifu_axi_arprot(ifu_axi_arprot_0),
    .ifu_axi_arqos(ifu_axi_arqos_0),
    .ifu_axi_rvalid(ifu_axi_rvalid_0),
    .ifu_axi_rready(ifu_axi_rready_0),
    .ifu_axi_rid(ifu_axi_rid_0),
    .ifu_axi_rdata(ifu_axi_rdata_0),
    .ifu_axi_rresp(ifu_axi_rresp_0),
    .ifu_axi_rlast(ifu_axi_rlast_0),
    .sb_axi_awvalid(sb_axi_awvalid_0),
    .sb_axi_awready(sb_axi_awready_0),
    .sb_axi_awid(sb_axi_awid_0),
    .sb_axi_awaddr(sb_axi_awaddr_0),
    .sb_axi_awregion(sb_axi_awregion_0),
    .sb_axi_awlen(sb_axi_awlen_0),
    .sb_axi_awsize(sb_axi_awsize_0),
    .sb_axi_awburst(sb_axi_awburst_0),
    .sb_axi_awlock(sb_axi_awlock_0),
    .sb_axi_awcache(sb_axi_awcache_0),
    .sb_axi_awprot(sb_axi_awprot_0),
    .sb_axi_awqos(sb_axi_awqos_0),
    .sb_axi_wvalid(sb_axi_wvalid_0),
    .sb_axi_wready(sb_axi_wready_0),
    .sb_axi_wdata(sb_axi_wdata_0),
    .sb_axi_wstrb(sb_axi_wstrb_0),
    .sb_axi_wlast(sb_axi_wlast_0),
    .sb_axi_bvalid(sb_axi_bvalid_0),
    .sb_axi_bready(sb_axi_bready_0),
    .sb_axi_bresp(sb_axi_bresp_0),
    .sb_axi_bid(sb_axi_bid_0),
    .sb_axi_arvalid(sb_axi_arvalid_0),
    .sb_axi_arready(sb_axi_arready_0),
    .sb_axi_arid(sb_axi_arid_0),
    .sb_axi_araddr(sb_axi_araddr_0),
    .sb_axi_arregion(sb_axi_arregion_0),
    .sb_axi_arlen(sb_axi_arlen_0),
    .sb_axi_arsize(sb_axi_arsize_0),
    .sb_axi_arburst(sb_axi_arburst_0),
    .sb_axi_arlock(sb_axi_arlock_0),
    .sb_axi_arcache(sb_axi_arcache_0),
    .sb_axi_arprot(sb_axi_arprot_0),
    .sb_axi_arqos(sb_axi_arqos_0),
    .sb_axi_rvalid(sb_axi_rvalid_0),
    .sb_axi_rready(sb_axi_rready_0),
    .sb_axi_rid(sb_axi_rid_0),
    .sb_axi_rdata(sb_axi_rdata_0),
    .sb_axi_rresp(sb_axi_rresp_0),
    .sb_axi_rlast(sb_axi_rlast_0),
    .dma_axi_awvalid(dma_axi_awvalid_0),
    .dma_axi_awready(dma_axi_awready_0),
    .dma_axi_awid(dma_axi_awid_0),
    .dma_axi_awaddr(dma_axi_awaddr_0),
    .dma_axi_awsize(dma_axi_awsize_0),
    .dma_axi_awprot(dma_axi_awprot_0),
    .dma_axi_awlen(dma_axi_awlen_0),
    .dma_axi_awburst(dma_axi_awburst_0),
    .dma_axi_wvalid(dma_axi_wvalid_0),
    .dma_axi_wready(dma_axi_wready_0),
    .dma_axi_wdata(dma_axi_wdata_0),
    .dma_axi_wstrb(dma_axi_wstrb_0),
    .dma_axi_wlast(dma_axi_wlast_0),
    .dma_axi_bvalid(dma_axi_bvalid_0),
    .dma_axi_bready(dma_axi_bready_0),
    .dma_axi_bresp(dma_axi_bresp_0),
    .dma_axi_bid(dma_axi_bid_0),
    .dma_axi_arvalid(dma_axi_arvalid_0),
    .dma_axi_arready(dma_axi_arready_0),
    .dma_axi_arid(dma_axi_arid_0),
    .dma_axi_araddr(dma_axi_araddr_0),
    .dma_axi_arsize(dma_axi_arsize_0),
    .dma_axi_arprot(dma_axi_arprot_0),
    .dma_axi_arlen(dma_axi_arlen_0),
    .dma_axi_arburst(dma_axi_arburst_0),
    .dma_axi_rvalid(dma_axi_rvalid_0),
    .dma_axi_rready(dma_axi_rready_0),
    .dma_axi_rid(dma_axi_rid_0),
    .dma_axi_rdata(dma_axi_rdata_0),
    .dma_axi_rresp(dma_axi_rresp_0),
    .dma_axi_rlast(dma_axi_rlast_0),
    .lsu_bus_clk_en(lsu_bus_clk_en_0),
    .ifu_bus_clk_en(ifu_bus_clk_en_0),
    .dbg_bus_clk_en(dbg_bus_clk_en_0),
    .dma_bus_clk_en(dma_bus_clk_en_0),
    .jtag_tck(jtag_tck_0),
    .jtag_tms(jtag_tms_0),
    .jtag_tdi(jtag_tdi_0),
    .jtag_trst_n(jtag_trst_n_0),
    .jtag_tdo(jtag_tdo_0),
    .extintsrc_req(extintsrc_req_0),
    .timer_int(timer_int_0),
    .scan_mode(scan_mode_0)
  );
  swerv u1 (
    .clk(clk),
    .rst_l(rst_l),
    .rst_vec(rst_vec_1),
    .nmi_int(nmi_int_1),
    .nmi_vec(nmi_vec_1),
    .jtag_id(jtag_id_1),
    .core_rst_l(core_rst_l_1),
    .trace_rv_i_insn_ip(trace_rv_i_insn_ip_1),
    .trace_rv_i_address_ip(trace_rv_i_address_ip_1),
    .trace_rv_i_valid_ip(trace_rv_i_valid_ip_1),
    .trace_rv_i_exception_ip(trace_rv_i_exception_ip_1),
    .trace_rv_i_ecause_ip(trace_rv_i_ecause_ip_1),
    .trace_rv_i_interrupt_ip(trace_rv_i_interrupt_ip_1),
    .trace_rv_i_tval_ip(trace_rv_i_tval_ip_1),
    .lsu_freeze_dc3(lsu_freeze_dc3_1),
    .dccm_clk_override(dccm_clk_override_1),
    .icm_clk_override(icm_clk_override_1),
    .dec_tlu_core_ecc_disable(dec_tlu_core_ecc_disable_1),
    .i_cpu_halt_req(i_cpu_halt_req_1),
    .i_cpu_run_req(i_cpu_run_req_1),
    .o_cpu_halt_ack(o_cpu_halt_ack_1),
    .o_cpu_halt_status(o_cpu_halt_status_1),
    .o_cpu_run_ack(o_cpu_run_ack_1),
    .o_debug_mode_status(o_debug_mode_status_1),
    .mpc_debug_halt_req(mpc_debug_halt_req_1),
    .mpc_debug_run_req(mpc_debug_run_req_1),
    .mpc_reset_run_req(mpc_reset_run_req_1),
    .mpc_debug_halt_ack(mpc_debug_halt_ack_1),
    .mpc_debug_run_ack(mpc_debug_run_ack_1),
    .debug_brkpt_status(debug_brkpt_status_1),
    .dec_tlu_perfcnt0(dec_tlu_perfcnt0_1),
    .dec_tlu_perfcnt1(dec_tlu_perfcnt1_1),
    .dec_tlu_perfcnt2(dec_tlu_perfcnt2_1),
    .dec_tlu_perfcnt3(dec_tlu_perfcnt3_1),
    .dccm_wren(dccm_wren_1),
    .dccm_rden(dccm_rden_1),
    .dccm_wr_addr(dccm_wr_addr_1),
    .dccm_rd_addr_lo(dccm_rd_addr_lo_1),
    .dccm_rd_addr_hi(dccm_rd_addr_hi_1),
    .dccm_wr_data(dccm_wr_data_1),
    .dccm_rd_data_lo(dccm_rd_data_lo_1),
    .dccm_rd_data_hi(dccm_rd_data_hi_1),
    .ic_rw_addr(ic_rw_addr_1),
    .ic_tag_valid(ic_tag_valid_1),
    .ic_wr_en(ic_wr_en_1),
    .ic_rd_en(ic_rd_en_1),
    .ic_wr_data(ic_wr_data_1),
    .ic_rd_data(ic_rd_data_1),
    .ictag_debug_rd_data(ictag_debug_rd_data_1),
    .ic_debug_wr_data(ic_debug_wr_data_1),
    .ic_premux_data(ic_premux_data_1),
    .ic_sel_premux_data(ic_sel_premux_data_1),
    .ic_debug_addr(ic_debug_addr_1),
    .ic_debug_rd_en(ic_debug_rd_en_1),
    .ic_debug_wr_en(ic_debug_wr_en_1),
    .ic_debug_tag_array(ic_debug_tag_array_1),
    .ic_debug_way(ic_debug_way_1),
    .ic_rd_hit(ic_rd_hit_1),
    .ic_tag_perr(ic_tag_perr_1),
    .lsu_axi_awvalid(lsu_axi_awvalid_1),
    .lsu_axi_awready(lsu_axi_awready_1),
    .lsu_axi_awid(lsu_axi_awid_1),
    .lsu_axi_awaddr(lsu_axi_awaddr_1),
    .lsu_axi_awregion(lsu_axi_awregion_1),
    .lsu_axi_awlen(lsu_axi_awlen_1),
    .lsu_axi_awsize(lsu_axi_awsize_1),
    .lsu_axi_awburst(lsu_axi_awburst_1),
    .lsu_axi_awlock(lsu_axi_awlock_1),
    .lsu_axi_awcache(lsu_axi_awcache_1),
    .lsu_axi_awprot(lsu_axi_awprot_1),
    .lsu_axi_awqos(lsu_axi_awqos_1),
    .lsu_axi_wvalid(lsu_axi_wvalid_1),
    .lsu_axi_wready(lsu_axi_wready_1),
    .lsu_axi_wdata(lsu_axi_wdata_1),
    .lsu_axi_wstrb(lsu_axi_wstrb_1),
    .lsu_axi_wlast(lsu_axi_wlast_1),
    .lsu_axi_bvalid(lsu_axi_bvalid_1),
    .lsu_axi_bready(lsu_axi_bready_1),
    .lsu_axi_bresp(lsu_axi_bresp_1),
    .lsu_axi_bid(lsu_axi_bid_1),
    .lsu_axi_arvalid(lsu_axi_arvalid_1),
    .lsu_axi_arready(lsu_axi_arready_1),
    .lsu_axi_arid(lsu_axi_arid_1),
    .lsu_axi_araddr(lsu_axi_araddr_1),
    .lsu_axi_arregion(lsu_axi_arregion_1),
    .lsu_axi_arlen(lsu_axi_arlen_1),
    .lsu_axi_arsize(lsu_axi_arsize_1),
    .lsu_axi_arburst(lsu_axi_arburst_1),
    .lsu_axi_arlock(lsu_axi_arlock_1),
    .lsu_axi_arcache(lsu_axi_arcache_1),
    .lsu_axi_arprot(lsu_axi_arprot_1),
    .lsu_axi_arqos(lsu_axi_arqos_1),
    .lsu_axi_rvalid(lsu_axi_rvalid_1),
    .lsu_axi_rready(lsu_axi_rready_1),
    .lsu_axi_rid(lsu_axi_rid_1),
    .lsu_axi_rdata(lsu_axi_rdata_1),
    .lsu_axi_rresp(lsu_axi_rresp_1),
    .lsu_axi_rlast(lsu_axi_rlast_1),
    .ifu_axi_awvalid(ifu_axi_awvalid_1),
    .ifu_axi_awready(ifu_axi_awready_1),
    .ifu_axi_awid(ifu_axi_awid_1),
    .ifu_axi_awaddr(ifu_axi_awaddr_1),
    .ifu_axi_awregion(ifu_axi_awregion_1),
    .ifu_axi_awlen(ifu_axi_awlen_1),
    .ifu_axi_awsize(ifu_axi_awsize_1),
    .ifu_axi_awburst(ifu_axi_awburst_1),
    .ifu_axi_awlock(ifu_axi_awlock_1),
    .ifu_axi_awcache(ifu_axi_awcache_1),
    .ifu_axi_awprot(ifu_axi_awprot_1),
    .ifu_axi_awqos(ifu_axi_awqos_1),
    .ifu_axi_wvalid(ifu_axi_wvalid_1),
    .ifu_axi_wready(ifu_axi_wready_1),
    .ifu_axi_wdata(ifu_axi_wdata_1),
    .ifu_axi_wstrb(ifu_axi_wstrb_1),
    .ifu_axi_wlast(ifu_axi_wlast_1),
    .ifu_axi_bvalid(ifu_axi_bvalid_1),
    .ifu_axi_bready(ifu_axi_bready_1),
    .ifu_axi_bresp(ifu_axi_bresp_1),
    .ifu_axi_bid(ifu_axi_bid_1),
    .ifu_axi_arvalid(ifu_axi_arvalid_1),
    .ifu_axi_arready(ifu_axi_arready_1),
    .ifu_axi_arid(ifu_axi_arid_1),
    .ifu_axi_araddr(ifu_axi_araddr_1),
    .ifu_axi_arregion(ifu_axi_arregion_1),
    .ifu_axi_arlen(ifu_axi_arlen_1),
    .ifu_axi_arsize(ifu_axi_arsize_1),
    .ifu_axi_arburst(ifu_axi_arburst_1),
    .ifu_axi_arlock(ifu_axi_arlock_1),
    .ifu_axi_arcache(ifu_axi_arcache_1),
    .ifu_axi_arprot(ifu_axi_arprot_1),
    .ifu_axi_arqos(ifu_axi_arqos_1),
    .ifu_axi_rvalid(ifu_axi_rvalid_1),
    .ifu_axi_rready(ifu_axi_rready_1),
    .ifu_axi_rid(ifu_axi_rid_1),
    .ifu_axi_rdata(ifu_axi_rdata_1),
    .ifu_axi_rresp(ifu_axi_rresp_1),
    .ifu_axi_rlast(ifu_axi_rlast_1),
    .sb_axi_awvalid(sb_axi_awvalid_1),
    .sb_axi_awready(sb_axi_awready_1),
    .sb_axi_awid(sb_axi_awid_1),
    .sb_axi_awaddr(sb_axi_awaddr_1),
    .sb_axi_awregion(sb_axi_awregion_1),
    .sb_axi_awlen(sb_axi_awlen_1),
    .sb_axi_awsize(sb_axi_awsize_1),
    .sb_axi_awburst(sb_axi_awburst_1),
    .sb_axi_awlock(sb_axi_awlock_1),
    .sb_axi_awcache(sb_axi_awcache_1),
    .sb_axi_awprot(sb_axi_awprot_1),
    .sb_axi_awqos(sb_axi_awqos_1),
    .sb_axi_wvalid(sb_axi_wvalid_1),
    .sb_axi_wready(sb_axi_wready_1),
    .sb_axi_wdata(sb_axi_wdata_1),
    .sb_axi_wstrb(sb_axi_wstrb_1),
    .sb_axi_wlast(sb_axi_wlast_1),
    .sb_axi_bvalid(sb_axi_bvalid_1),
    .sb_axi_bready(sb_axi_bready_1),
    .sb_axi_bresp(sb_axi_bresp_1),
    .sb_axi_bid(sb_axi_bid_1),
    .sb_axi_arvalid(sb_axi_arvalid_1),
    .sb_axi_arready(sb_axi_arready_1),
    .sb_axi_arid(sb_axi_arid_1),
    .sb_axi_araddr(sb_axi_araddr_1),
    .sb_axi_arregion(sb_axi_arregion_1),
    .sb_axi_arlen(sb_axi_arlen_1),
    .sb_axi_arsize(sb_axi_arsize_1),
    .sb_axi_arburst(sb_axi_arburst_1),
    .sb_axi_arlock(sb_axi_arlock_1),
    .sb_axi_arcache(sb_axi_arcache_1),
    .sb_axi_arprot(sb_axi_arprot_1),
    .sb_axi_arqos(sb_axi_arqos_1),
    .sb_axi_rvalid(sb_axi_rvalid_1),
    .sb_axi_rready(sb_axi_rready_1),
    .sb_axi_rid(sb_axi_rid_1),
    .sb_axi_rdata(sb_axi_rdata_1),
    .sb_axi_rresp(sb_axi_rresp_1),
    .sb_axi_rlast(sb_axi_rlast_1),
    .dma_axi_awvalid(dma_axi_awvalid_1),
    .dma_axi_awready(dma_axi_awready_1),
    .dma_axi_awid(dma_axi_awid_1),
    .dma_axi_awaddr(dma_axi_awaddr_1),
    .dma_axi_awsize(dma_axi_awsize_1),
    .dma_axi_awprot(dma_axi_awprot_1),
    .dma_axi_awlen(dma_axi_awlen_1),
    .dma_axi_awburst(dma_axi_awburst_1),
    .dma_axi_wvalid(dma_axi_wvalid_1),
    .dma_axi_wready(dma_axi_wready_1),
    .dma_axi_wdata(dma_axi_wdata_1),
    .dma_axi_wstrb(dma_axi_wstrb_1),
    .dma_axi_wlast(dma_axi_wlast_1),
    .dma_axi_bvalid(dma_axi_bvalid_1),
    .dma_axi_bready(dma_axi_bready_1),
    .dma_axi_bresp(dma_axi_bresp_1),
    .dma_axi_bid(dma_axi_bid_1),
    .dma_axi_arvalid(dma_axi_arvalid_1),
    .dma_axi_arready(dma_axi_arready_1),
    .dma_axi_arid(dma_axi_arid_1),
    .dma_axi_araddr(dma_axi_araddr_1),
    .dma_axi_arsize(dma_axi_arsize_1),
    .dma_axi_arprot(dma_axi_arprot_1),
    .dma_axi_arlen(dma_axi_arlen_1),
    .dma_axi_arburst(dma_axi_arburst_1),
    .dma_axi_rvalid(dma_axi_rvalid_1),
    .dma_axi_rready(dma_axi_rready_1),
    .dma_axi_rid(dma_axi_rid_1),
    .dma_axi_rdata(dma_axi_rdata_1),
    .dma_axi_rresp(dma_axi_rresp_1),
    .dma_axi_rlast(dma_axi_rlast_1),
    .lsu_bus_clk_en(lsu_bus_clk_en_1),
    .ifu_bus_clk_en(ifu_bus_clk_en_1),
    .dbg_bus_clk_en(dbg_bus_clk_en_1),
    .dma_bus_clk_en(dma_bus_clk_en_1),
    .jtag_tck(jtag_tck_1),
    .jtag_tms(jtag_tms_1),
    .jtag_tdi(jtag_tdi_1),
    .jtag_trst_n(jtag_trst_n_1),
    .jtag_tdo(jtag_tdo_1),
    .extintsrc_req(extintsrc_req_1),
    .timer_int(timer_int_1),
    .scan_mode(scan_mode_1)
  );
endmodule
